# Analytics Configuration
# Cloud Scale Analytics Documentation Monitoring

analytics:
  # General Settings
  enabled: true
  environment: production  # development, staging, production
  debug_mode: false
  sample_rate: 1.0  # 100% sampling
  
  # Data Collection
  collection:
    # Page Views
    page_views:
      enabled: true
      track_query_params: false
      excluded_params:
        - token
        - key
        - password
      track_hash_changes: true
      track_virtual_pages: true
    
    # User Journey
    user_journey:
      enabled: true
      max_journey_length: 50
      session_timeout_minutes: 30
      track_referrers: true
      track_exit_links: true
    
    # Search Analytics
    search:
      enabled: true
      track_queries: true
      track_results: true
      track_clicks: true
      track_refinements: true
      zero_results_tracking: true
    
    # Scroll Tracking
    scroll:
      enabled: true
      thresholds: [25, 50, 75, 100]
      debounce_ms: 100
      track_depth: true
      track_velocity: false
    
    # Time Tracking
    time:
      enabled: true
      track_active_time: true
      track_total_time: true
      idle_threshold_seconds: 30
      heartbeat_interval_seconds: 30
    
    # Interaction Tracking
    interactions:
      clicks:
        enabled: true
        track_all_links: true
        track_buttons: true
        track_forms: false
      
      downloads:
        enabled: true
        file_extensions:
          - pdf
          - zip
          - docx
          - xlsx
      
      media:
        enabled: true
        track_play: true
        track_pause: true
        track_complete: true
        track_progress: true
    
    # Error Tracking
    errors:
      javascript_errors: true
      api_errors: true
      resource_errors: true
      max_errors_per_session: 100
      include_stack_trace: true
      
  # Performance Monitoring
  performance:
    enabled: true
    
    # Core Web Vitals
    web_vitals:
      track_lcp: true  # Largest Contentful Paint
      track_fid: true  # First Input Delay
      track_cls: true  # Cumulative Layout Shift
      track_fcp: true  # First Contentful Paint
      track_ttfb: true # Time to First Byte
      track_inp: true  # Interaction to Next Paint
    
    # Resource Timing
    resources:
      enabled: true
      sample_rate: 0.5  # Sample 50% of resources
      track_critical_resources: true
      size_threshold_kb: 100
      duration_threshold_ms: 1000
    
    # Custom Metrics
    custom_metrics:
      enabled: true
      allowed_metrics:
        - search_latency
        - api_response_time
        - render_time
        - data_fetch_time
  
  # Segmentation
  segmentation:
    # User Segments
    user_segments:
      enabled: true
      dimensions:
        - new_vs_returning
        - device_category
        - browser_family
        - os_family
        - country
        - language
    
    # Content Segments
    content_segments:
      enabled: true
      dimensions:
        - page_category
        - content_type
        - documentation_version
        - product_area
    
    # Technical Segments
    technical_segments:
      enabled: true
      dimensions:
        - connection_type
        - screen_resolution
        - viewport_size
        - color_depth
  
  # Custom Dimensions
  custom_dimensions:
    - name: doc_version
      index: 1
      scope: hit
    - name: user_role
      index: 2
      scope: session
    - name: content_category
      index: 3
      scope: hit
    - name: search_category
      index: 4
      scope: hit
    - name: experiment_variant
      index: 5
      scope: session
  
  # Custom Events
  custom_events:
    - name: feedback_submitted
      category: engagement
      parameters:
        - rating
        - comment_length
        - feedback_type
    
    - name: search_performed
      category: search
      parameters:
        - query
        - results_count
        - filters_used
    
    - name: content_copied
      category: engagement
      parameters:
        - content_type
        - content_length
        - page_section
    
    - name: video_watched
      category: media
      parameters:
        - video_id
        - watch_percentage
        - duration
  
  # Filters and Exclusions
  filters:
    # IP Exclusions
    exclude_ips:
      - 192.168.0.0/16
      - 10.0.0.0/8
      - 172.16.0.0/12
    
    # User Agent Exclusions
    exclude_user_agents:
      - bot
      - crawler
      - spider
      - monitoring
      - synthetic
    
    # Path Exclusions
    exclude_paths:
      - /admin/*
      - /api/*
      - /health
      - /metrics
      - *.xml
      - *.txt
    
    # Referrer Exclusions
    exclude_referrers:
      - localhost
      - 127.0.0.1
      - staging.microsoft.com
  
  # Data Processing
  processing:
    # Batch Processing
    batch:
      enabled: true
      size: 100
      interval_seconds: 30
      max_retry: 3
      retry_delay_ms: 1000
    
    # Real-time Processing
    realtime:
      enabled: true
      endpoints:
        - /api/analytics/realtime
      buffer_size: 50
      flush_interval_ms: 5000
    
    # Data Enrichment
    enrichment:
      geo_location: true
      device_detection: true
      bot_detection: true
      company_detection: false
      content_classification: true
  
  # Storage
  storage:
    # Primary Storage
    primary:
      type: postgresql  # postgresql, mysql, mongodb, bigquery
      connection_string: ${DATABASE_URL}
      pool_size: 10
      timeout_seconds: 30
    
    # Archive Storage
    archive:
      enabled: true
      type: azure_blob  # s3, azure_blob, gcs
      container: analytics-archive
      retention_days: 730  # 2 years
      compression: gzip
    
    # Cache Storage
    cache:
      enabled: true
      type: redis
      ttl_seconds: 3600
      max_entries: 10000
  
  # API Configuration
  api:
    enabled: true
    base_url: /api/analytics
    version: v1
    
    # Rate Limiting
    rate_limiting:
      enabled: true
      requests_per_minute: 1000
      burst_size: 100
    
    # Authentication
    authentication:
      required: false
      methods:
        - api_key
        - oauth2
    
    # CORS
    cors:
      enabled: true
      allowed_origins:
        - https://microsoft.github.io
        - https://docs.microsoft.com
      allowed_methods:
        - GET
        - POST
      allowed_headers:
        - Content-Type
        - Authorization
  
  # Reporting
  reporting:
    # Standard Reports
    standard_reports:
      enabled: true
      types:
        - overview
        - pages
        - users
        - search
        - performance
        - errors
    
    # Custom Reports
    custom_reports:
      enabled: true
      max_custom_reports: 50
    
    # Scheduled Reports
    scheduled_reports:
      enabled: true
      max_scheduled_reports: 20
      delivery_methods:
        - email
        - webhook
        - storage
    
    # Export Formats
    export_formats:
      - json
      - csv
      - xlsx
      - pdf
      - html
  
  # Alerting
  alerting:
    enabled: true
    
    # Alert Rules
    rules:
      - name: high_error_rate
        metric: error_rate
        threshold: 0.05
        duration_minutes: 5
        severity: critical
      
      - name: slow_page_load
        metric: avg_load_time
        threshold: 5000
        duration_minutes: 10
        severity: warning
      
      - name: traffic_spike
        metric: page_views_per_minute
        threshold: 1000
        duration_minutes: 5
        severity: info
    
    # Notification Channels
    channels:
      - type: email
        recipients:
          - alerts@microsoft.com
        enabled: true
      
      - type: slack
        webhook: ${SLACK_WEBHOOK_URL}
        channel: "#docs-alerts"
        enabled: false
      
      - type: teams
        webhook: ${TEAMS_WEBHOOK_URL}
        enabled: true
  
  # Integration
  integrations:
    # Google Analytics (fallback)
    google_analytics:
      enabled: false
      tracking_id: UA-XXXXXXXXX-X
      
    # Application Insights
    application_insights:
      enabled: true
      instrumentation_key: ${APP_INSIGHTS_KEY}
      role_name: docs-analytics
      
    # Custom Integrations
    custom:
      - name: documentation_cms
        enabled: true
        endpoint: /api/cms/analytics
        events:
          - page_publish
          - content_update
          - version_release
  
  # A/B Testing
  ab_testing:
    enabled: true
    
    # Experiments
    experiments:
      - name: new_navigation
        enabled: true
        traffic_percentage: 50
        variants:
          - control
          - variant_a
        metrics:
          - bounce_rate
          - pages_per_session
          - search_usage
      
      - name: content_format
        enabled: false
        traffic_percentage: 33
        variants:
          - standard
          - enhanced
          - minimal
  
  # Machine Learning
  ml_features:
    enabled: true
    
    # Predictive Analytics
    predictive:
      bounce_prediction: true
      content_recommendations: true
      search_suggestions: true
    
    # Anomaly Detection
    anomaly_detection:
      enabled: true
      metrics:
        - page_views
        - error_rate
        - load_time
      sensitivity: medium
    
    # Clustering
    user_clustering:
      enabled: true
      algorithm: kmeans
      features:
        - pages_viewed
        - time_on_site
        - search_queries
      num_clusters: 5
  
  # Debug and Development
  debug:
    enabled: false
    verbose_logging: false
    console_output: false
    save_raw_events: false
    test_mode: false
    
    # Development Overrides
    dev_overrides:
      disable_sampling: true
      force_https: false
      skip_validation: false
      mock_data: false