# Privacy and GDPR Configuration
# Cloud Scale Analytics Documentation Monitoring

privacy:
  # General Privacy Settings
  enabled: true
  mode: strict  # strict, balanced, minimal
  compliance:
    - GDPR
    - CCPA
    - LGPD
  
  # Data Collection Settings
  data_collection:
    # User Identification
    user_identification:
      method: anonymous  # anonymous, pseudonymous, identified
      hash_ip: true
      hash_user_agent: true
      use_cookies: false  # Cookie-less tracking
      fingerprinting: false
    
    # Personal Data Handling
    personal_data:
      collect_pii: false
      anonymize_immediately: true
      encryption: AES-256
      secure_transmission: true
    
    # Data Minimization
    data_minimization:
      enabled: true
      fields_to_exclude:
        - email
        - name
        - phone
        - address
        - credit_card
        - ssn
      regex_patterns:
        - '\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b'  # Email
        - '\b\d{3}-\d{2}-\d{4}\b'  # SSN
        - '\b\d{4}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}\b'  # Credit card
    
    # Consent Management
    consent:
      required: true
      default_state: denied
      granular_options:
        analytics: true
        performance: true
        functionality: true
        marketing: false
      cookie_banner:
        enabled: true
        position: bottom
        style: minimal
        reshow_after_days: 365
    
  # Data Storage
  data_storage:
    # Retention Policies
    retention:
      default_days: 90
      by_data_type:
        page_views: 90
        user_sessions: 30
        errors: 180
        feedback: 365
        performance: 60
      auto_delete: true
      deletion_batch_size: 1000
    
    # Storage Security
    security:
      encryption_at_rest: true
      encryption_in_transit: true
      access_control: RBAC
      audit_logging: true
      backup_encryption: true
    
    # Data Location
    location:
      primary: US  # US, EU, UK, etc.
      restrict_cross_border: true
      allowed_regions:
        - US
        - EU
        - UK
      data_residency: true
  
  # User Rights (GDPR Articles 15-22)
  user_rights:
    # Right to Access (Article 15)
    access:
      enabled: true
      self_service: true
      response_time_days: 30
      format: JSON
      verification_required: true
    
    # Right to Rectification (Article 16)
    rectification:
      enabled: true
      self_service: false
      response_time_days: 30
    
    # Right to Erasure (Article 17)
    erasure:
      enabled: true
      self_service: true
      response_time_days: 30
      cascade_delete: true
      retain_legal_basis: true
    
    # Right to Restrict Processing (Article 18)
    restriction:
      enabled: true
      self_service: true
      immediate_effect: true
    
    # Right to Data Portability (Article 20)
    portability:
      enabled: true
      formats:
        - JSON
        - CSV
        - XML
      self_service: true
      response_time_days: 30
    
    # Right to Object (Article 21)
    objection:
      enabled: true
      types:
        - direct_marketing
        - profiling
        - automated_decisions
      immediate_effect: true
  
  # Third-Party Sharing
  third_party:
    sharing_enabled: false
    processors: []
    sub_processors: []
    data_transfer_agreements: []
  
  # Breach Management
  breach_management:
    detection:
      enabled: true
      monitoring_interval: 300  # seconds
      alert_threshold: 100  # suspicious events
    
    notification:
      authorities:
        enabled: true
        contact: privacy@dataprotection.gov
        deadline_hours: 72
      
      users:
        enabled: true
        method: email
        deadline_hours: 72
        template: breach_notification.html
    
    documentation:
      required: true
      retention_years: 5
      include_items:
        - breach_description
        - affected_data
        - affected_users
        - mitigation_steps
        - prevention_measures
  
  # Privacy by Design
  privacy_by_design:
    data_minimization: true
    purpose_limitation: true
    pseudonymization: true
    transparency: true
    security_first: true
    privacy_default: true
  
  # Legal Basis
  legal_basis:
    analytics:
      basis: legitimate_interest
      description: "Improve documentation quality and user experience"
      balancing_test_performed: true
    
    performance:
      basis: legitimate_interest
      description: "Ensure optimal documentation performance"
      balancing_test_performed: true
    
    feedback:
      basis: consent
      description: "Collect user feedback to improve content"
      withdrawal_allowed: true
  
  # Data Protection Officer
  dpo:
    appointed: true
    name: "Data Protection Officer"
    email: dpo@microsoft.com
    phone: "+1-555-0123"
    public_contact: privacy@microsoft.com
  
  # Privacy Notice
  privacy_notice:
    url: https://privacy.microsoft.com/privacystatement
    version: "2.0"
    last_updated: "2025-01-01"
    languages:
      - en
      - es
      - fr
      - de
      - pt
      - it
      - ja
      - zh
    easy_read_version: true
    children_version: false

# Audit and Compliance
audit:
  enabled: true
  frequency: quarterly
  external_audit: annual
  certifications:
    - "ISO 27001"
    - "SOC 2 Type II"
    - "Privacy Shield"
  
  logs:
    retention_days: 2555  # 7 years
    immutable: true
    encryption: true
    access_restricted: true

# Cookie Policy (if cookies are used)
cookies:
  enabled: false  # Cookie-less by default
  types:
    necessary:
      enabled: true
      consent_required: false
      cookies: []
    
    analytics:
      enabled: false
      consent_required: true
      cookies: []
    
    functional:
      enabled: false
      consent_required: true
      cookies: []
    
    marketing:
      enabled: false
      consent_required: true
      cookies: []

# Anonymization Rules
anonymization:
  techniques:
    - k_anonymity
    - l_diversity
    - differential_privacy
  
  k_anonymity:
    k_value: 5
    quasi_identifiers:
      - country
      - browser_family
      - os_family
  
  differential_privacy:
    epsilon: 1.0
    sensitivity: 1.0
    noise_mechanism: laplace
  
  ip_anonymization:
    enabled: true
    method: truncate  # truncate, hash, remove
    ipv4_octets_to_remove: 1
    ipv6_octets_to_remove: 2

# Consent Management Platform
consent_management:
  provider: internal  # internal, onetrust, cookiebot, etc.
  
  banner:
    title: "Your Privacy Matters"
    description: "We use privacy-preserving analytics to improve documentation. No personal data is collected."
    accept_text: "Accept"
    reject_text: "Reject"
    customize_text: "Customize"
    learn_more_link: "/privacy-policy"
  
  granular_controls:
    show_toggle: true
    allow_partial_consent: true
    remember_choice_days: 365
  
  api:
    check_consent_endpoint: /api/consent/check
    update_consent_endpoint: /api/consent/update
    get_preferences_endpoint: /api/consent/preferences

# Regional Compliance
regional_compliance:
  auto_detect: true
  
  EU:
    apply_gdpr: true
    cookie_consent_required: true
    data_location: EU
    retention_days: 90
  
  California:
    apply_ccpa: true
    do_not_sell: true
    opt_out_visible: true
    retention_days: 365
  
  Brazil:
    apply_lgpd: true
    consent_required: true
    data_location: BR
    retention_days: 180
  
  default:
    privacy_mode: balanced
    consent_required: false
    retention_days: 180

# Testing and Validation
testing:
  privacy_tests:
    enabled: true
    frequency: weekly
    tests:
      - pii_detection
      - consent_flow
      - data_deletion
      - anonymization_effectiveness
      - cross_border_transfer
  
  compliance_validation:
    enabled: true
    automated_checks: true
    manual_review: quarterly